# changing prefix from control +b to shift plus q
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# vertical split
bind V split-window -v
#horizontal split
bind H split-window -h
##unbinding previous
unbind '"'
unbind %

#navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#reloading the config
bind r source-file ~/.tmux.conf
