[config]
reload_apps = false
reload_apps_list = []
# set_wallpaper = false

[config.reload]

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.local/state/safalQuick/colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.local/state/safalQuick/kitty.conf"
post_hook = 'pkill -SIGUSR1 kitty'

[templates.monkeytype]
input_path  = "~/.config/matugen/templates/monkeytype.json"
output_path = "~/.local/state/safalQuick/monkeytype.json"

[templates.hyprland]
input_path  = "~/.config/matugen/templates/colors.lua"
output_path = "~/.config/hypr/conf/colors.lua"
post_hook = 'hyprctl reload'

[templates.obsidian]
input_path  = "~/.config/matugen/templates/obsidian.css"
output_path ="~/toughNot/notes/.obsidian/snippets/style.css"
