[config]
reload_apps = false
reload_apps_list = []
# set_wallpaper = false

[config.reload]

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.cache/safalQuick/colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.cache/safalQuick/kitty.conf"
post_hook = 'pkill -SIGUSR1 kitty'

[templates.monkeytype]
input_path  = "~/.config/matugen/templates/monkeytype.json"
output_path = "~/.cache/safalQuick/monkeytype.json"
# post_hook = "~/.config/quickshell/Scripts/monkeymode.py"

[templates.hyprland]
input_path  = "~/.config/matugen/templates/general.conf"
output_path = "~/.config/hypr/conf.d/general.conf"
post_hook = "hyprctl reload"

[templates.obsidian]
input_path  = "~/.config/matugen/templates/obsidian.css"
output_path ="~/toughNot/notes/.obsidian/snippets/style.css"
