require("conf.animation")
require("conf.overview")
require("conf.autostart")
require("conf.decoration")
require("conf.device")
require("conf.env")
require("conf.layerrules")
-- require("conf.plugin")
require("conf.gestures")
require("conf.keybinds")
require("conf.dvd")
require("conf.layout")
require("conf.misc")
require("conf.monitor")
require("conf.windowrules")
require("conf.workspace")
require("conf.general")
