general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(f9acfaee) rgba(ffb3b1ee) 45deg
    col.inactive_border = rgba(5d3f3eaa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
