general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(ffb689ee) rgba(cacb79ee) 45deg
    col.inactive_border = rgba(52443baa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
